### ISSUE TITLE
Problem with Alexa integration (haaska)

### ISSUE THREAD

**Issue by OcioRanocio** [o0Zz/ha-melcloud#12]
Hi! I'm using Alexa Integration (haaska).
I can control my Mitsubishi but Alexa always says that the device doesn't respond.
I've found that it works correctly if I modify the file climate.py like this:

OPERATION_HEAT_STR = ‘heat’
OPERATION_COOL_STR = ‘cool’
OPERATION_FAN_STR = ‘fan’
OPERATION_AUTO_STR = ‘auto’
OPERATION_OFF_STR = ‘off’
OPERATION_DRY_STR = ‘dry’

No capital letters.
Do you think you can change that?
Thank You

**Comment by o0Zz** [comment]
Hi, 

Thank you for your feedback, do you have any other control (Heatpump or other) you can control with Alexa? Does it use Capital letter or not ?

My concern is to make sure this issue is not a temporary issue from HA.
I tried to looked in HA source code and a lot of climates use capital letter.
So, I will keep your issue opened and if I see HA plugins moves to lower case I will move too.

Let me know if you can still reproduce this issue in several weeks.

Thanks

**Comment by OcioRanocio** [comment]
Hi!
Thank you for your super fast answer.
I have a Nest Thermostat and I can see in the operation_list: off,heat,eco 

In HA log I see:
2019-06-13 19:59:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=climate, service=turn_on, service_data=entity_id=climate.melcloud_sala_XXXXXX>
2019-06-13 19:59:13 ERROR (MainThread) [homeassistant.components.alexa.smart_home] climate.melcloud_sala_XXXXXX (<class 'homeassistant.core.State'>) has unsupported operation_mode value 'Off'
2019-06-13 19:59:13 ERROR (MainThread) [aiohttp.server] Error handling request

Doing some google research, I stumbled on (same error message/different climate entity):
https://github.com/home-assistant/home-assistant/issues/14175
In the end they say standard is lowercase (even if I don't know if it is true and where to check it)

So if it doesn't ruin something else, I think you can change it

Thank you very much for your work.
I will let you know if things change in the future

**Comment by o0Zz** [comment]
Hi, 

Melcloud component now uses HA constants (Which use no capital letters)
So, you should not deal with this issue anymore. 
Let me know if you can reproduce it with this new component version.

BR
